### ISSUE TITLE
Definir schema de base de datos, objetos y conexión

### ISSUE THREAD

**Issue by gayoso** [BigFiuBrother/big-fiubrother-core#1]
Por ahora usamos una relacional con PostgreSQL.

**Comment by eduardoneira** [comment]
Meti en el core sql alchemy. Permite crear objetos python para encapsular tablas de la BDD. Por ahora meti la table de video chunks. Hay que definir que más necesitamos

**Comment by gayoso** [comment]
## BDD:

### VIDEO CHUNKS:
	id
	camera_id
	timestamp
	payload

### FRAMES:
	id
	video_chunk_id (VIDEO CHUNK fk)
	offset

### PEOPLE:
	id
	name

### DETECTED FACES:
	id
	frame_id (FRAME fk)
	bbox
	embedding
	classification_id (PEOPLE fk)
	classification_prob

### INTERPOLATED VIDEO CHUNKS:
	id
	video_chunk_id (VIDEO CHUNK fk UNIQUE)
	payload

**Comment by eduardoneira** [comment]
Definidas las clases y modelos de la base de datos
